### ISSUE TITLE
Closing a disconnected SPED-3 generates error.

### ISSUE THREAD

**Issue by Lucus16** [HerobrinesArmy/DevCPU#24]
Platform: Linux x86_64 gtk2
When you close a disconnected SPED-3 view, it generates this error in the Eclipse console:

Exception in thread "Thread-3" org.lwjgl.LWJGLException: X Error - disp: 0x7f589408e680 serial: 189 error: BadWindow (invalid Window parameter) request_code: 2 minor_code: 0
    at org.lwjgl.opengl.LinuxDisplay.globalErrorHandler(LinuxDisplay.java:318)
    at org.lwjgl.opengl.LinuxKeyboard.nSetDetectableKeyRepeat(Native Method)
    at org.lwjgl.opengl.LinuxKeyboard.setDetectableKeyRepeat(LinuxKeyboard.java:152)
    at org.lwjgl.opengl.LinuxKeyboard.destroy(LinuxKeyboard.java:163)
    at org.lwjgl.opengl.LinuxDisplay.destroyKeyboard(LinuxDisplay.java:1203)
    at org.lwjgl.input.Keyboard.destroy(Keyboard.java:349)
    at org.lwjgl.opengl.Display.destroyWindow(Display.java:346)
    at org.lwjgl.opengl.Display.access$400(Display.java:62)
    at org.lwjgl.opengl.Display$5.destroy(Display.java:832)
    at org.lwjgl.opengl.Display.destroy(Display.java:1083)
    at devcpu.emulation.SPED3Viewer$2.run(SPED3Viewer.java:155)

After this, DevCPU keeps working, however if you try to make a new SPED-3 viewer, it will show an interface-light-gray or white screen instead of the usual black and it will generate another error:

Exception in thread "Thread-6" java.lang.IllegalStateException: The Drawable has no context available.
    at org.lwjgl.opengl.DrawableGL.checkDestroyed(DrawableGL.java:152)
    at org.lwjgl.opengl.DrawableGL.makeCurrent(DrawableGL.java:109)
    at org.lwjgl.opengl.Display.makeCurrent(Display.java:703)
    at org.lwjgl.opengl.Display.makeCurrentAndSetSwapInterval(Display.java:1022)
    at org.lwjgl.opengl.Display.setParent(Display.java:449)
    at devcpu.emulation.SPED3Viewer$2.run(SPED3Viewer.java:61)

After that, DevCPU still keeps working but crashes rather easily.

**Comment by HerobrinesArmy** [comment]
I am unable to reproduce this issue on Windows, but I'll look into it and see if I can figure out what's causing it on Linux.

**Comment by HerobrinesArmy** [comment]
I've updated the LWJGL used by DevCPU to the last successful nightly build. I'm rebuilding the Mac versions and the plugin this morning so I might go ahead and rebuild the Linux builds while I'm at it; we'll see.

**Comment by HerobrinesArmy** [comment]
I did rebuild the Linux builds as well, by the way, a couple of days ago and those builds do include a bleeding-edge LWJGL. I'd be interested to hear if this new build has any effect on any LWJGL-related errors people were seeing on Linux.

**Comment by Lucus16** [comment]
Just pulled and tested, seems this didn't fix it...

**Comment by HerobrinesArmy** [comment]
Oh well. Maybe it will go away when I rework the rendering thread to behave like the new LEM1802 view.
